### ISSUE TITLE
Overriding defaults

### ISSUE THREAD

**Issue by Leif-Frederiksen** [Voitanos/jest-preset-spfx-react15#5]
Hi Andrew,

In order for my devops pipeline to publish the coverage report, I want to add the cobertura coverage reporter like this:
  "coverageReporters": [
    "json",
    "lcov",
    "text-summary"**,
    "cobertura"**
  ],

I do not want to copy the whole jest-preset.json file to make this change - that would disable me from future improvements from your hand.
Is there a way to create some config file, that is "added" to the setup described in the jest-preset.json file that I reference?

Regards
Leif

**Comment by Leif-Frederiksen** [comment]
Hey - found the answer myself:
Override desired parameters in config/jest.config.json. To achieve the request regarding coevrage, the file should be like this:
```
{
  "preset": "@voitanos/jest-preset-spfx-react16",
  "rootDir": "../src",
  "coverageReporters": [
    "json",
    "lcov",
    "text-summary",
    "cobertura"
  ]
}
```

**Comment by andrewconnell** [comment]
Yup, that would have been my answer as well, as that's how I'm overriding the `rootDir` property in the preset.
