### ISSUE TITLE
Compilation errors after installing Jest with the preset15 on a 2019 solution

### ISSUE THREAD

**Issue by fguicc** [Voitanos/jest-preset-spfx-react15#6]
Hi Andrew, this is what I did:
1. Creation of a new spfx solution using yeoman (3.1.0)
- SharePoint 2019 onwards
- WebPart
- React

2. The solution of course builds and I'm able to test it.

3. Then I run "npm install jest @voitanos/jest-preset-spfx-react15 --save-dev"

4. The solution still builds

5. Then I add a .test.ts file with the code from "Option 2: Create your own test"
and I get erros building

> [10:35:02] Warning - tslint - src\webparts\helloJest2019\test\HelloJest2019.test.ts(4,9): error typedef: expected variable-declaration: 'result' to have a typedef
> [10:35:02] Warning - tslint - src\webparts\helloJest2019\test\HelloJest2019.test.ts(4,19): error whitespace: missing whitespace
> [10:35:02] Warning - tslint - src\webparts\helloJest2019\test\HelloJest2019.test.ts(4,20): error whitespace: missing whitespace
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(16,139): error TS1110: Type expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(16,146): error TS1138: Parameter declaration expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(16,155): error TS1005: ';' expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(16,156): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(16,165): error TS1005: '=' expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(33,17): error TS1110: Type expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(33,24): error TS1138: Parameter declaration expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(33,33): error TS1005: ';' expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(33,34): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\BufferedConsole.d.ts(33,43): error TS1005: '=' expected.
> [10:35:04] Error - typescript - node_modules\@jest\console\build\getConsoleOutput.d.ts(6,65): error TS1110: Type expected.
> [10:35:04] Error - typescript - node_modules\@jest\core\build\cli\index.d.ts(9,36): error TS1110: Type expected.
> [10:35:04] Error - typescript - node_modules\@jest\core\build\cli\index.d.ts(10,16): error TS1005: ',' expected.
> 

I did the same steps for an SPO only solution and the react16 preset and everything worked fine

**Comment by andrewconnell** [comment]
These are all issues related to TypeScript and type declarations... appears you have a newer version of Jest / TypeScript installed in your project that's confusing things. Can you share your **package.json** to see what versions you have setup in your project?

**Comment by fguicc** [comment]
These are the package.json and the package-lock.json
I did not modify anything manually...
[package.zip](https://github.com/Voitanos/jest-preset-spfx-react15/files/3670896/package.zip)

**Comment by andrewconnell** [comment]
Can you please just copy-paste the CONTENTS of the **package.json** to a comment? Don't need the lock file. _I'm not downloading a ZIP from an unknown source :)_

**Comment by fguicc** [comment]
yes sorry,
here it is:

{
  "name": "hello-jest",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "./node_modules/.bin/jest --config ./config/jest.config.json",
    "test:watch": "./node_modules/.bin/jest --config ./config/jest.config.json --watchAll"
  },
  "dependencies": {
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "office-ui-fabric-react": "6.189.2",
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-webpart-base": "1.9.1",
    "@microsoft/sp-lodash-subset": "1.9.1",
    "@microsoft/sp-office-ui-fabric-core": "1.9.1",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  },
  "resolutions": {
    "@types/react": "16.8.8"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-2.9": "0.7.16",
    "@microsoft/sp-build-web": "1.9.1",
    "@microsoft/sp-module-interfaces": "1.9.1",
    "@microsoft/sp-tslint-rules": "1.9.1",
    "@microsoft/sp-webpart-workbench": "1.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "@voitanos/jest-preset-spfx-react16": "^1.2.0",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "jest": "^24.9.0"
  }
}

**Comment by andrewconnell** [comment]
_editted comment to make it readable by adding GH code fencing_

You said in the OP that you were using the react15 preset... that's what this project is for. But your **package.json** says you're using react16, plus your project is using react 16, not react 15. Furthermore, you say SP2019... but this project uses SPFx v1.9.1... that's not going to work. SP2019 only supports SPFx v1.4.1

There's a bunch of stuff here to fix before I take a look at a potential issue.

**Comment by fguicc** [comment]
I'm sorry I copied the package.json from the SPO only project with react 16 and your preset, that is working fine, no issues.

I have updated the comment with the package.json, now it shows the right one from the SP2019 solution.

Can you please have a look?

Thanks in advance

**Comment by andrewconnell** [comment]
_Again, in the future... please use code fencing to format the code you paste to make it clear what is code, and to make it readable. I've edited your comment again as you removed the fencing I added previously._

I've made a change to the library, it's now v1.2. The problems you were running into were dependent on TypeScript type declarations, versions of TypeScript, and other versioning issues. The changes lock you down to specific versions. The challenge is you're effectively frozen in time, but no much you can do with that. When you're on SP2019 you're stuck with SPFx v1.4.1 and React 15 which means you're also stuck with TypeScript 2.4.2.

To fix, I'd rip it out and add it back:

```shell
# uninstall what you have
npm uninstall jest @voitanos/jest-preset-spfx-react15

# delete node_modules & anby package manager lock files

# install specific version of jest & use exact versions, not wildcards
npm install jest@23.6.0 @voitanos/jest-preset-spfx-react15 --save-dev --save-exact
```

Now add your tests and run the test.

> NOTE: the example tests in the README & in the package were also updated to pass tslint rules.

**Comment by fguicc** [comment]
Thank you very much.
I tested again creating an new SP2019 solution from scratch, gulp compiles and "npm test" is able to run the tests.
There is one step that is **mandatory** to make it work: remove the _package-lock.json_ before running the command
`npm install jest@23.6.0 @voitanos/jest-preset-spfx-react15 --save-dev --save-exact`

**Comment by andrewconnell** [comment]
@fguicc said:
> There is one step that is mandatory to make it work: remove the package-lock.json before running the command

Yup, that's why I said it in my above comment :)

**Comment by ajardimdev** [comment]
I love you @andrewconnell ! <3
